<?php

namespace App\Models\Entities;

use Illuminate\Database\Eloquent\Model;

class School extends Model {
    public $timestamps = true;
    protected $fillable = ['name', 'code', 'address'];

    public function __toString()
    {
        return $this->name; // TODO: Change the autogenerated stub
    }

    public function students()
    {
        return $this->hasMany(Student::class);
    }
}
