<?php

namespace App\Models\Entities;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    public $timestamps = true;
    protected $fillable = ['name', 'lastname', 'age', 'grade', 'is_active', 'school_id'];

    public function __toString()
    {
        return $this->name; // TODO: Change the autogenerated stub
    }

    public function school()
    {
        return $this->belongsTo(School::class);
    }
}
